from __future__ import annotations

import argparse
from pathlib import Path
import sys

from agent_libos.api.cli import _build_cli_parser


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "cli_reference.md"
_USAGE_WIDTH = 88
_HEADER = """# Generated CLI Reference

<!-- Generated by scripts/generate_cli_reference.py. Do not edit directly. -->

This is the exhaustive command and argument inventory for the checked-in
`agent-libos` parser. For task-oriented explanations and security semantics,
use the [CLI Guide](cli.md). Defaults shown here are parser defaults; effective
Runtime settings may additionally come from `DEFAULT_CONFIG`, `config.yaml`, or
an explicit `--config` overlay as described in the
[Configuration Guide](configuration.md). Usage wrapping and metavars are
normalized across supported Python versions; every accepted option alias is
listed in the Arguments tables.
"""


def _markdown_text(value: str | None) -> str:
    if not value:
        return "—"
    return " ".join(value.split()).replace("|", "\\|")


def _code(value: object) -> str:
    escaped = str(value).replace("|", "\\|").replace("`", "\\`")
    return f"`{escaped}`"


def _heading_anchor(value: str) -> str:
    normalized = "".join(
        character
        for character in value.lower()
        if character.isalnum() or character in {" ", "-", "_"}
    )
    return "-".join(normalized.split())


def _required(action: argparse.Action) -> bool:
    if action.option_strings:
        return bool(action.required)
    return action.nargs not in {"?", "*"}


def _default(action: argparse.Action) -> str:
    if action.default is argparse.SUPPRESS:
        return "—"
    return _code(repr(action.default))


def _metavar(action: argparse.Action) -> tuple[str, ...]:
    if action.metavar is not None:
        if isinstance(action.metavar, tuple):
            return tuple(str(item) for item in action.metavar)
        return (str(action.metavar),)
    if action.choices is not None:
        return ("{" + ",".join(str(choice) for choice in action.choices) + "}",)
    default = action.dest.upper() if action.option_strings else action.dest
    return (default,)


def _value_syntax(action: argparse.Action) -> str:
    nargs = action.nargs
    if nargs == 0:
        return ""
    metavars = _metavar(action)
    if nargs is None:
        if len(metavars) != 1:
            raise ValueError(f"{action.dest}: nargs=None requires one metavar")
        return metavars[0]
    if nargs == "?":
        if len(metavars) != 1:
            raise ValueError(f"{action.dest}: nargs='?' requires one metavar")
        return f"[{metavars[0]}]"
    if nargs == "*":
        if len(metavars) != 1:
            raise ValueError(f"{action.dest}: nargs='*' requires one metavar")
        return f"[{metavars[0]} ...]"
    if nargs == "+":
        if len(metavars) != 1:
            raise ValueError(f"{action.dest}: nargs='+' requires one metavar")
        return f"{metavars[0]} [{metavars[0]} ...]"
    if nargs == argparse.REMAINDER:
        if len(metavars) != 1:
            raise ValueError(f"{action.dest}: remainder requires one metavar")
        return f"{metavars[0]} ..."
    if isinstance(nargs, int):
        if len(metavars) == 1:
            return " ".join(metavars * nargs)
        if len(metavars) == nargs:
            return " ".join(metavars)
        raise ValueError(
            f"{action.dest}: nargs={nargs} requires one or {nargs} metavars"
        )
    raise ValueError(f"{action.dest}: unsupported nargs value {nargs!r}")


def _argument_syntax(action: argparse.Action) -> str:
    value = _value_syntax(action)
    if not action.option_strings:
        return value
    options = ", ".join(action.option_strings)
    return f"{options} {value}" if value else options


def _usage_atom(action: argparse.Action) -> str:
    if isinstance(action, argparse._SubParsersAction):
        if action.metavar is not None:
            command = str(action.metavar)
        else:
            command = "{" + ",".join(str(name) for name in action.choices) + "}"
        return f"{command} ..."

    value = _value_syntax(action)
    if not action.option_strings:
        return value
    if isinstance(action, argparse.BooleanOptionalAction):
        option = " | ".join(action.option_strings)
    else:
        option = action.option_strings[0]
    return f"{option} {value}" if value else option


def _usage_fragment(action: argparse.Action) -> str:
    atom = _usage_atom(action)
    if action.option_strings and not action.required:
        return f"[{atom}]"
    if isinstance(action, argparse._SubParsersAction) and not action.required:
        return f"[{atom}]"
    return atom


def _subcommand_help(action: argparse._SubParsersAction) -> dict[str, str]:
    help_by_parser_id = {
        id(action.choices[str(choice.dest)]): _markdown_text(choice.help)
        for choice in action._choices_actions
        if str(choice.dest) in action.choices
    }
    return {
        str(name): help_by_parser_id.get(id(parser), "—")
        for name, parser in action.choices.items()
    }


def _format_usage(parser: argparse.ArgumentParser) -> str:
    if parser.usage is not None:
        usage = str(parser.usage).replace("%(prog)s", parser.prog)
        return f"usage: {usage}"

    group_for_action: dict[int, tuple[int, bool, list[argparse.Action]]] = {}
    for group in parser._mutually_exclusive_groups:
        visible_actions = [
            action for action in group._group_actions if action.help is not argparse.SUPPRESS
        ]
        for action in visible_actions:
            group_for_action[id(action)] = (id(group), group.required, visible_actions)

    fragments: list[str] = []
    rendered_groups: set[int] = set()
    for action in parser._actions:
        if action.help is argparse.SUPPRESS:
            continue
        grouped = group_for_action.get(id(action))
        if grouped is None:
            fragments.append(_usage_fragment(action))
            continue
        group_id, required, group_actions = grouped
        if group_id in rendered_groups:
            continue
        rendered_groups.add(group_id)
        alternatives = " | ".join(_usage_atom(item) for item in group_actions)
        fragments.append(
            f"({alternatives})" if required else f"[{alternatives}]"
        )

    prefix = f"usage: {parser.prog}"
    continuation = " " * (len(prefix) + 1)
    lines: list[str] = []
    current = prefix
    for fragment in fragments:
        candidate = f"{current} {fragment}"
        if len(candidate) <= _USAGE_WIDTH:
            current = candidate
            continue
        lines.append(current)
        current = f"{continuation}{fragment}"
    lines.append(current)
    return "\n".join(lines)


def _render_parser(parser: argparse.ArgumentParser) -> list[str]:
    usage = _format_usage(parser)
    lines = [f"## `{parser.prog}`", "", "```text", usage, "```", ""]
    if parser.description:
        lines.extend([_markdown_text(parser.description), ""])

    ordinary_actions = [
        action
        for action in parser._actions
        if not isinstance(action, argparse._SubParsersAction)
    ]
    if ordinary_actions:
        lines.extend(
            [
                "### Arguments",
                "",
                "| Syntax | Required | Default | Description |",
                "| --- | --- | --- | --- |",
            ]
        )
        for action in ordinary_actions:
            syntax = _argument_syntax(action)
            lines.append(
                "| "
                + " | ".join(
                    (
                        _code(syntax),
                        "yes" if _required(action) else "no",
                        _default(action),
                        _markdown_text(action.help),
                    )
                )
                + " |"
            )
        lines.append("")

    subparser_actions = [
        action
        for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    ]
    for action in subparser_actions:
        help_by_name = _subcommand_help(action)
        lines.extend(
            [
                "### Subcommands",
                "",
                "| Command | Description |",
                "| --- | --- |",
            ]
        )
        for name in action.choices:
            lines.append(
                f"| {_code(name)} | {help_by_name.get(name, '—')} |"
            )
        lines.append("")
    return lines


def _walk_parsers(parser: argparse.ArgumentParser) -> list[argparse.ArgumentParser]:
    parsers: list[argparse.ArgumentParser] = []
    seen: set[int] = set()

    def visit(current: argparse.ArgumentParser) -> None:
        identity = id(current)
        if identity in seen:
            return
        seen.add(identity)
        parsers.append(current)
        for action in current._actions:
            if not isinstance(action, argparse._SubParsersAction):
                continue
            for child in action.choices.values():
                visit(child)

    visit(parser)
    return parsers


def _top_level_parsers(
    parser: argparse.ArgumentParser,
) -> list[argparse.ArgumentParser]:
    parsers = [parser]
    seen = {id(parser)}
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for child in action.choices.values():
            identity = id(child)
            if identity in seen:
                continue
            seen.add(identity)
            parsers.append(child)
    return parsers


def render_cli_reference() -> str:
    parser = _build_cli_parser()
    indexed_parsers = _top_level_parsers(parser)
    indexed_sections = [
        (current.prog, _heading_anchor(current.prog))
        for current in indexed_parsers
    ]
    labels = [label for label, _anchor in indexed_sections]
    anchors = [anchor for _label, anchor in indexed_sections]
    if len(labels) != len(set(labels)) or len(anchors) != len(set(anchors)):
        raise RuntimeError("generated top-level CLI index entries must be unique")

    lines = [
        _HEADER.rstrip(),
        "",
        "[documentation home](index.md)",
        "",
        "## Command index",
        "",
        *(f"- [`{label}`](#{anchor})" for label, anchor in indexed_sections),
        "",
    ]
    for current in _walk_parsers(parser):
        lines.extend(_render_parser(current))
    return "\n".join(lines).rstrip() + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate the exhaustive Markdown reference for agent-libos."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when docs/cli_reference.md is stale",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    expected = render_cli_reference()
    if args.check:
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        if current != expected:
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this script without --check",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(ROOT)} is current")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
