from __future__ import annotations

import argparse
from collections.abc import Mapping
from dataclasses import MISSING, fields, is_dataclass
import json
from pathlib import Path
import sys
import types
from typing import Annotated, Any, Literal, Union, get_args, get_origin, get_type_hints

from pydantic import Strict

from agent_libos.config import AgentLibOSConfig, DEFAULT_CONFIG


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "configuration_reference.md"
_HEADER = """# Generated Configuration Field Reference

<!-- Generated by scripts/generate_config_reference.py. Do not edit directly. -->

This inventory is generated from the checked-in frozen configuration
dataclasses. It is exhaustive for declared field paths and resolved Python
annotations, and it records every scalar default. Short scalar collections are
shown inline; other collection defaults are summarized, with nested dataclass
templates expanded below their container paths. Use the live dump command below
when exact collection contents matter. Loading, precedence, validation
semantics, security handling, and subsystem-specific constraints are normative
in the [Configuration Guide](configuration.md).

Configuration has no hot reload: any change requires construction of a new
Runtime. A unit-bearing name segment supplies the unit only where the table says
so (`_s` seconds, `_ms` milliseconds, `_bytes` bytes, `_chars` characters,
`_tokens` tokens, and `_quanta` scheduler quanta). Fields without a listed unit
are counts, enums, identifiers, paths, policies, ratios, or other values defined
by the guide and typed source.

Exact checked-in baseline defaults can be inspected without opening a Runtime:

```bash
uv run python - <<'PY'
import json
from agent_libos.config import DEFAULT_CONFIG
from agent_libos.utils.serde import to_jsonable

print(json.dumps(to_jsonable(DEFAULT_CONFIG), indent=2, sort_keys=True))
PY
```
"""


def _markdown(value: str) -> str:
    return value.replace("|", "\\|").replace("`", "\\`")


def _heading_anchor(value: str) -> str:
    normalized = "".join(
        character
        for character in value.lower()
        if character.isalnum() or character in {" ", "-", "_"}
    )
    return "-".join(normalized.split())


def _type_name(annotation: Any) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        base, *metadata = args
        if any(isinstance(item, Strict) and item.strict for item in metadata):
            strict_names = {
                int: "StrictInt",
                float: "StrictFloat",
                bool: "StrictBool",
            }
            if base in strict_names:
                return strict_names[base]
        return _type_name(base)
    if origin in {Union, types.UnionType}:
        return " | ".join(_type_name(item) for item in args)
    if origin is Literal:
        return "Literal[" + ", ".join(repr(item) for item in args) + "]"
    if origin is not None:
        name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        if args:
            rendered = ", ".join(
                "..." if item is Ellipsis else _type_name(item) for item in args
            )
            return f"{name}[{rendered}]"
        return name
    if annotation is Any:
        return "Any"
    if annotation is None or annotation is type(None):
        return "None"
    return getattr(annotation, "__name__", str(annotation).replace("typing.", ""))


def _default_text(value: Any) -> str:
    if value is MISSING:
        return "required"
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, Mapping):
        if not value:
            return "{}"
        keys = ", ".join(
            sorted(json.dumps(str(key), ensure_ascii=False) for key in value)
        )
        return f"mapping with {len(value)} default key(s): {keys}"
    if isinstance(value, (tuple, list, set, frozenset)):
        sequence = list(value)
        if isinstance(value, (set, frozenset)):
            sequence.sort(key=repr)
        if not sequence:
            return "[]"
        if len(sequence) <= 4 and all(
            item is None or isinstance(item, (bool, int, float, str)) for item in sequence
        ):
            return json.dumps(sequence, ensure_ascii=False)
        return f"{len(sequence)} default item(s); inspect DEFAULT_CONFIG for exact values"
    if is_dataclass(value):
        return f"{type(value).__name__} defaults; see template fields below"
    return repr(value)


def _unit(path: str) -> str:
    name = path.rsplit(".", 1)[-1]
    for marker, unit in (
        ("_bytes", "bytes"),
        ("_chars", "characters"),
        ("_tokens", "tokens"),
        ("_quanta", "quanta"),
    ):
        if marker in name:
            return unit
    if name.endswith("_ms"):
        return "milliseconds"
    if name.endswith(("_s", "_seconds")):
        return "seconds"
    return "—"


def _dataclass_template(
    annotation: Any,
) -> tuple[type[Any], tuple[str, ...]] | None:
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return _dataclass_template(args[0])
    if origin in {Union, types.UnionType}:
        candidates = {
            candidate
            for item in args
            if (candidate := _dataclass_template(item)) is not None
        }
        if len(candidates) > 1:
            raise TypeError(
                f"ambiguous dataclass template annotation cannot be rendered: {annotation!r}"
            )
        return next(iter(candidates)) if candidates else None
    if origin is None:
        if isinstance(annotation, type) and is_dataclass(annotation):
            return annotation, ()
        return None
    if origin in {dict, Mapping} or (
        isinstance(origin, type) and issubclass(origin, Mapping)
    ):
        nested = _dataclass_template(args[-1]) if args else None
        if nested is None:
            return None
        template, segments = nested
        return template, ("<key>", *segments)
    if origin in {tuple, list, set, frozenset}:
        nested = _dataclass_template(args[0]) if args else None
        if nested is None:
            return None
        template, segments = nested
        return template, ("<item>", *segments)
    return None


def _field_default(field: Any, instance: Any | None) -> Any:
    if instance is not None:
        return getattr(instance, field.name)
    if field.default is not MISSING:
        return field.default
    if field.default_factory is not MISSING:
        return field.default_factory()
    return MISSING


def _rows_for_dataclass(
    cls: type[Any],
    *,
    prefix: str,
    instance: Any | None,
) -> list[tuple[str, str, str, str]]:
    hints = get_type_hints(cls, include_extras=True)
    rows: list[tuple[str, str, str, str]] = []
    for field in fields(cls):
        annotation = hints[field.name]
        value = _field_default(field, instance)
        path = f"{prefix}.{field.name}" if prefix else field.name
        if is_dataclass(value):
            rows.extend(
                _rows_for_dataclass(type(value), prefix=path, instance=value)
            )
            continue
        rows.append((path, _type_name(annotation), _default_text(value), _unit(path)))
        template = _dataclass_template(annotation)
        if template is not None:
            template_cls, segments = template
            try:
                template_instance = template_cls()
            except (TypeError, ValueError):
                template_instance = None
            template_prefix = ".".join((path, *segments))
            rows.extend(
                _rows_for_dataclass(
                    template_cls,
                    prefix=template_prefix,
                    instance=template_instance,
                )
            )
    return rows


def render_config_reference() -> str:
    rows = _rows_for_dataclass(
        AgentLibOSConfig,
        prefix="",
        instance=DEFAULT_CONFIG,
    )
    paths = [row[0] for row in rows]
    if len(paths) != len(set(paths)):
        raise RuntimeError("generated configuration paths must be unique")
    by_section: dict[str, list[tuple[str, str, str, str]]] = {}
    for row in rows:
        by_section.setdefault(row[0].split(".", 1)[0], []).append(row)

    indexed_sections = [
        (section, _heading_anchor(section)) for section in by_section
    ]
    anchors = [anchor for _section, anchor in indexed_sections]
    if len(anchors) != len(set(anchors)):
        raise RuntimeError("generated configuration group index anchors must be unique")

    lines = [
        _HEADER.rstrip(),
        "",
        "[documentation home](index.md)",
        "",
        "## Configuration group index",
        "",
        *(
            f"- [`{section}`](#{anchor})"
            for section, anchor in indexed_sections
        ),
        "",
    ]
    for section, section_rows in by_section.items():
        lines.extend(
            [
                f"## `{section}`",
                "",
                "| Path | Type | Default | Unit |",
                "| --- | --- | --- | --- |",
            ]
        )
        for path, type_name, default, unit in section_rows:
            lines.append(
                f"| `{_markdown(path)}` | `{_markdown(type_name)}` | "
                f"`{_markdown(default)}` | {unit} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate the exhaustive Agent libOS configuration field reference."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when docs/configuration_reference.md is stale",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    expected = render_config_reference()
    if args.check:
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        if current != expected:
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this script without --check",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(ROOT)} is current")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
