from __future__ import annotations

import argparse
from pathlib import Path, PurePosixPath
import re
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_URL = "https://github.com/yingqi-z20/Agent-libOS"
SOURCE_README = "README.md"
PYPI_README = "README.pypi.md"
_GENERATED_HEADER = (
    "<!-- Generated by scripts/generate_pypi_readme.py from README.md. "
    "Do not edit directly. -->\n\n"
)
_MARKDOWN_LINK = re.compile(r"(?P<prefix>!?\[[^\]]*\]\()(?P<target>[^)]+)(?P<suffix>\))")
_FINAL_VERSION = re.compile(r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\Z")
_PROJECT_CLONE = re.compile(r"git clone " + re.escape(REPOSITORY_URL) + r"(?:\.git)?")


def _project_version(root: Path) -> str:
    value = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))[
        "project"
    ]["version"]
    version = str(value)
    if _FINAL_VERSION.fullmatch(version) is None:
        raise ValueError("PyPI README generation requires a final X.Y.Z version")
    return version


def _split_optional_title(target: str) -> tuple[str, str]:
    # Markdown permits an optional quoted title after the destination.  The
    # repository currently avoids it, but preserving it makes this generator
    # safe for future prose changes.
    match = re.fullmatch(r"(\S+)(\s+(?:\"[^\"]*\"|'[^']*'|\([^)]*\)))?", target)
    if match is None:
        raise ValueError(f"unsupported Markdown link target: {target!r}")
    return match.group(1), match.group(2) or ""


def _versioned_target(destination: str, *, version: str) -> str:
    if destination.startswith(("https://", "http://", "mailto:", "#")):
        mutable_prefix = f"{REPOSITORY_URL}/blob/main/"
        if destination.startswith(mutable_prefix):
            return f"{REPOSITORY_URL}/blob/v{version}/{destination.removeprefix(mutable_prefix)}"
        return destination
    if destination.startswith("/") or "\\" in destination:
        raise ValueError(f"README repository link is not a portable relative path: {destination}")
    path_text, separator, fragment = destination.partition("#")
    normalized = PurePosixPath(path_text.removeprefix("./"))
    if not normalized.parts or any(part in {"", ".", ".."} for part in normalized.parts):
        raise ValueError(f"README repository link is not a safe relative path: {destination}")
    suffix = f"#{fragment}" if separator else ""
    return f"{REPOSITORY_URL}/blob/v{version}/{normalized.as_posix()}{suffix}"


def render_pypi_readme(source: str, *, version: str) -> str:
    if _FINAL_VERSION.fullmatch(version) is None:
        raise ValueError("PyPI README generation requires a final X.Y.Z version")

    def replace(match: re.Match[str]) -> str:
        destination, title = _split_optional_title(match.group("target"))
        rewritten = _versioned_target(destination, version=version)
        return f'{match.group("prefix")}{rewritten}{title}{match.group("suffix")}'

    rendered = _GENERATED_HEADER + _MARKDOWN_LINK.sub(replace, source)

    def pin_clone(match: re.Match[str]) -> str:
        # The package-index README must reproduce against the immutable release
        # tag, so a bare `git clone <repo>` is pinned to `--branch v<version>`.
        return match.group(0).replace("git clone ", f"git clone --branch v{version} ", 1)

    rendered = _PROJECT_CLONE.sub(pin_clone, rendered)
    if _PROJECT_CLONE.search(rendered):
        raise ValueError("generated PyPI README contains an unpinned project git clone")
    mutable_prefix = f"{REPOSITORY_URL}/blob/main/"
    if mutable_prefix in rendered:
        raise ValueError("generated PyPI README contains a mutable main-branch link")
    return rendered


def generate(root: Path = ROOT) -> str:
    source = (root / SOURCE_README).read_text(encoding="utf-8")
    return render_pypi_readme(source, version=_project_version(root))


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the PyPI long description with repository links pinned "
            "to the release version tag."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when README.pypi.md is stale",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    expected = generate(ROOT)
    output = ROOT / PYPI_README
    if args.check:
        try:
            current = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"{PYPI_README} is missing; run this script without --check", file=sys.stderr)
            return 1
        if current != expected:
            print(f"{PYPI_README} is stale; run this script without --check", file=sys.stderr)
            return 1
        print(f"{PYPI_README} is current")
        return 0
    output.write_text(expected, encoding="utf-8")
    print(f"wrote {PYPI_README}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
